### ISSUE TITLE
You can't currently use Thrift for RPC in Unity

### ISSUE THREAD

**Issue by reverofevil** [amilstead/unity3d-thrift-twisted#1]
Thrift generates synchronous API for client-side. Each call is executed in the main Unity3D thread, so your framerate depends on how much the network is lagging. In every sane use case this solution is inappropriate.

It's possible to generate asynchronous API with Thrift, setting generator to `csharp:async` or `csharp:async_ctp`, but neither of these could be used with .NET 2.0 (Mono) included in Unity.

**Comment by amilstead** [comment]
Hey @polkovnikov-ph -- thanks for filing this issue.

I'd like to clear some things up here.

> It's possible to generate asynchronous API with Thrift, setting generator to `csharp:async` or `csharp:async_ctp`, but neither of these could be used with .NET 2.0 (Mono) included in Unity.

While that's 100% true, I'm not sure I quite grasp the real issue here. It's widely known that Unity uses Mono, which uses a _subset_ of .NET modules. Can you shed some light on what library usage inside the async packages won't work? Also, while naive synchronous TCP usage will most definitely block the main rendering thread, there are a ton of strategies that are available to users that will allow for non-blocking network access. In particular, [Coroutines](http://docs.unity3d.com/Manual/Coroutines.html) are pretty nice.

People have written blog posts about this: https://briksins.wordpress.com/2014/03/25/unity-networking-async-vs-coroutine/

> In every sane use case this solution is inappropriate.

Is that necessarily true? I can think of plenty of use cases where blocking network calls are 100% appropriate (i.e. login, registration, in app purchases, etc). Moreover, it's probably not wise to use something as heavy weight as TCP during an intensive graphics loop in the first place. A lot of folks have defaulted to UDP for that kind of network communication.

This is an example repository, and does not assert that it has "production ready" code. Its purpose is simply to demonstrate that usage of Thrift inside Unity3D is possible and provide an example of an implementation.

**Comment by reverofevil** [comment]
> Can you shed some light on what library usage inside the async packages won't work?

`System.Threading.Tasks` is absent in the version of Mono used by Unity 5. Mono compiler doesn't recognize `async` and `await` keywords either.

> Also, while naive synchronous TCP usage will most definitely block the main rendering thread, there are a ton of strategies that are available to users that will allow for non-blocking network access. In particular, Coroutines are pretty nice.

Sure, it would be nice _if_ Thrift generator for C# supported code generation for coroutines. But currently there are three options:
- `csharp`: synchronous calls that block rendering thread. It's a bad idea to implement any workarounds to make this work properly, as such extra code counterweights all profit gained by using Thrift for RPC.
- `csharp:async`: generates code with `async`/`await` such that it is impossible to use it in Unity.
- `csharp:asyncctp`: generates code for Async CTP that requires VS2010 SP1 with no further updates, and pretty useless for the sake of our target.

> Is that necessarily true? I can think of plenty of use cases where blocking network calls are 100% appropriate (i.e. login, registration, in app purchases, etc).

Yep, for such simple cases it should work OK, as well as simple `WWW` class that's already present in Unity. I'm talking about more diverse area of online game programming.

> Moreover, it's probably not wise to use something as heavy weight as TCP during an intensive graphics loop in the first place.

Does TCP per se slow down the graphics loop that much?

> A lot of folks have defaulted to UDP for that kind of network communication.

UDP is nice when you care about latency in networks with high amount of packet loss. That's mostly FPS or RTS online games, and Unity is in no way suited for these.

> This is an example repository, and does not assert that it has "production ready" code.

I've thought that you may be unaware that synchronous functions block rendering thread. This issue doesn't show up on developer PC due to low latency of loopback interface. Probably this should be claimed somewhere on the main page, so that less experienced Unity programmers would be aware of it too.

**Comment by alex-jawbone** [comment]
> Sure, it would be nice if Thrift generator for C# supported code generation for coroutines.

I think this is missing the point a bit. Coroutines are a mechanism for using IO bound resources in a "shared-IO" fashion. In effect, the code sort of feels asynchronous when it really isn't.

Whether or not Thrift has the capability of generating library code that utilizes coroutines is kind of irrelevant. 

Unless, as you mentioned, you specifically use the async version of Thrift, the generated code just wraps the transport in an object. That object and its callers are still perfectly valid and usable from inside a coroutine, or an "async worker" (in reference to the afore mentioned blog post).

> Yep, for such simple cases it should work OK, as well as simple WWW class that's already present in Unity. I'm talking about more diverse area of online game programming.

I'd be loathe to think anyone would use something as slow and cumbersome as even the simplest implementation of data transfer over an HTTP protocol in a networked game. Even those games that employ less "diverse networking game programming" should know better than that.

> Does TCP per se slow down the graphics loop that much?

A fair point; a TCP socket itself doesn't necessarily slow down the graphics loop "that much". The rhetoric here was that TCP-based network communications are generally better suited for streaming, which would imply a long running listener loop. Trying to pigeon-hole that into a rendering thread is what would slow things down.

I was agreeing with you here -- in that _blocking_ TCP doesn't belong in a rendering thread. That said, in lieu of [select](http://linux.die.net/man/2/select)-based sockets, TCP (by definition) will block threads on connection and shut-down (barring any naughty usage of the network stack). 

However -- In Unity, there are ways to avoid blocking the rendering thread while still using "blocking" network IO. Not to mention, [Unity3D supports Socket.Select](http://wiki.unity3d.com/index.php/NetworkCursor#C.23_-_Plugins.2FServer.cs).



> That's mostly FPS or RTS online games, and Unity is in no way suited for these.

That seems a bit heavy handed and mostly inaccurate. Unity3D is, effectively, a managed rendering loop. That has nothing to do with whether or not your code is suited for one game type or another.

Just because it's not the CryEngine or UnrealEngine, doesn't mean you can't write a decent FPS/RTS with it.

In fact, Unity's core networking stack is modeled almost __specifically__ after lobby style, peer-based server networking that is prevalent among most modern FPS/RTS games.

> I've thought that you may be unaware that synchronous functions block rendering thread. This issue doesn't show up on developer PC due to low latency of loopback interface. 

Thanks for the concern! I'm well aware of the difference between synchronous and asynchronous network communications, as well as the concept of a rendering loop, and the fact that Unity is a "single threaded" renderer.

> Probably this should be claimed somewhere on the main page, so that less experienced Unity programmers would be aware of it too.

The very first line of this project's README, is "This is a demo codebase"; demo == demonstration != production.

This code never claimed to be a framework or even a third-party package to include in your project (and is not structured as such). It's an example project that accompanied a blog post where I investigated whether or not I could use Thrift inside Unity3D .

**Comment by amilstead** [comment]
> Sure, it would be nice if Thrift generator for C# supported code generation for coroutines.

I think this is missing the point a bit. Coroutines are a mechanism for using IO bound resources in a "shared-IO" fashion. In effect, the code sort of feels asynchronous when it really isn't.

Whether or not Thrift has the capability of generating library code that utilizes coroutines is kind of irrelevant. 

Unless, as you mentioned, you specifically use the async version of Thrift, the generated code just wraps the transport in an object. That object and its callers are still perfectly valid and usable from inside a coroutine, or an "async worker" (in reference to the afore mentioned blog post).

> Yep, for such simple cases it should work OK, as well as simple WWW class that's already present in Unity. I'm talking about more diverse area of online game programming.

I'd be loathe to think anyone would use something as slow and cumbersome as even the simplest implementation of data transfer over an HTTP protocol in a networked game. Even those games that employ less "diverse networking game programming" should know better than that.

> Does TCP per se slow down the graphics loop that much?

A fair point; a TCP socket itself doesn't necessarily slow down the graphics loop "that much". The rhetoric here was that TCP-based network communications are generally better suited for streaming, which would imply a long running listener loop. Trying to pigeon-hole that into a rendering thread is what would slow things down.

I was agreeing with you here -- in that _blocking_ TCP doesn't belong in a rendering thread. That said, in lieu of [select](http://linux.die.net/man/2/select)-based sockets, TCP (by definition) will block threads on connection and shut-down (barring any naughty usage of the network stack). 

However -- In Unity, there are ways to avoid blocking the rendering thread while still using "blocking" network IO. Not to mention, [Unity3D supports Socket.Select](http://wiki.unity3d.com/index.php/NetworkCursor#C.23_-_Plugins.2FServer.cs).

> That's mostly FPS or RTS online games, and Unity is in no way suited for these.

That seems a bit heavy handed and mostly inaccurate. Unity3D is, effectively, a managed rendering loop. That has nothing to do with whether or not your code is suited for one game type or another.

Just because it's not the CryEngine or UnrealEngine, doesn't mean you can't write a decent FPS/RTS with it.

In fact, Unity's core networking stack is modeled almost **specifically** after lobby style, peer-based server networking that is prevalent among most modern FPS/RTS games.

> I've thought that you may be unaware that synchronous functions block rendering thread. This issue doesn't show up on developer PC due to low latency of loopback interface. 

Thanks for the concern! I'm well aware of the difference between synchronous and asynchronous network communications, as well as the concept of a rendering loop, and the fact that Unity is a "single threaded" renderer.

> Probably this should be claimed somewhere on the main page, so that less experienced Unity programmers would be aware of it too.

The very first line of this project's README, is "This is a demo codebase"; demo == demonstration != production.

This code never claimed to be a framework or even a third-party package to include in your project (and is not structured as such). It's an example project that accompanied a blog post where I investigated whether or not I could use Thrift inside Unity3D .
